import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/loaders/DRACOLoader.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/controls/OrbitControls.js';
import * as SkeletonUtils from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/utils/SkeletonUtils.js';

const DATA = [
 {key:'butterfly',name:'Butterfly',latin:'Danaus plexippus',order:'Lepidoptera',family:'Nymphalidae',range:'Worldwide',role:'Pollinator',diet:'Nectar',size:'8.5–10.5 cm',life:'2–6 weeks adult',color:0xffa63d,card:'butterfly.jpg',summary:'A pollinator whose wing scales create visual signalling, camouflage and thermoregulation.',note:'Pollination, food webs and seasonal migration make butterflies valuable ecological indicators.',anatomy:[['HEAD + ANTENNAE','Sensory antennae and compound eyes orient the butterfly toward odours, movement and light.','SENSORY SYSTEM'],['WING SURFACE','Microscopic wing scales scatter light and contribute to colour, signalling and camouflage.','FLIGHT SURFACE'],['THORAX + ABDOMEN','Flight muscles sit in the thorax while the abdomen contains major digestive and reproductive organs.','CORE BODY']]},
 {key:'bee',name:'Honey Bee',latin:'Apis mellifera',order:'Hymenoptera',family:'Apidae',range:'Worldwide',role:'Pollinator',diet:'Nectar + pollen',size:'12–15 mm',life:'~6 weeks worker',color:0xf1b84b,card:'bee.jpg',summary:'A social pollinator with a specialised pollen basket and complex colony communication.',note:'Bees support flowering plant reproduction and form tightly coordinated social colonies.',anatomy:[['HEAD + EYES','Compound eyes detect motion and colour while antennae provide chemical and tactile information.','SENSORY SYSTEM'],['WINGS + FLIGHT MUSCLES','Two pairs of wings are coupled in flight; rapid wing beats support hovering and precise navigation.','FLIGHT SYSTEM'],['ABDOMEN + STINGER','The abdomen houses digestive and reproductive organs; workers have a defensive stinger.','DEFENCE + CORE']]},
 {key:'ant',name:'Ant',latin:'Formica rufa',order:'Hymenoptera',family:'Formicidae',range:'Europe + Asia',role:'Soil engineer',diet:'Omnivorous',size:'4–9 mm',life:'Weeks–years',color:0xb46d45,card:'ant.jpg',summary:'A colony-driven soil engineer with extreme cooperative behaviour and specialised caste roles.',note:'Ants aerate soil, redistribute nutrients and help shape microhabitats.',anatomy:[['HEAD + MANDIBLES','The head carries sensory antennae and powerful mandibles used for feeding, defence and carrying.','SENSORY + TOOLS'],['THORAX + LEGS','The thorax anchors six jointed legs that provide traction and rapid ground locomotion.','LOCOMOTION'],['ABDOMEN','The abdomen contains major internal organs and chemical communication structures used by the colony.','CORE BODY']]},
 {key:'dragonfly',name:'Dragonfly',latin:'Anax imperator',order:'Odonata',family:'Aeshnidae',range:'Africa + Eurasia',role:'Predator',diet:'Predatory insects',size:'66–84 mm',life:'Weeks–months adult',color:0x54bdc4,card:'dragonfly.jpg',summary:'A precision aerial predator with independent wing control and exceptional visual acuity.',note:'Dragonflies are efficient aerial predators and useful signals of freshwater ecosystem health.',anatomy:[['HEAD + COMPOUND EYES','Huge compound eyes provide a wide visual field for tracking prey during aerial pursuit.','VISION SYSTEM'],['FOUR WINGS','Each wing can contribute independently to lift, braking and manoeuvring for precise aerial control.','FLIGHT SYSTEM'],['ABDOMEN','The long abdomen balances the body in flight and carries respiratory, digestive and reproductive systems.','CORE BODY']]},
 {key:'ladybug',name:'Ladybird',latin:'Coccinella septempunctata',order:'Coleoptera',family:'Coccinellidae',range:'Northern Hemisphere',role:'Biocontrol',diet:'Aphids',size:'5–8 mm',life:'1 year',color:0xe14f48,card:'ladybug.jpg',summary:'A compact beetle whose warning colours advertise chemical defences to predators.',note:'Ladybirds help regulate aphid populations and can protect crops naturally.',anatomy:[['HEAD + ANTENNAE','The small head carries compound eyes and short antennae that help locate prey and environmental cues.','SENSORY SYSTEM'],['ELYTRA + WINGS','The coloured wing covers protect folded flight wings beneath the hard beetle shell.','ARMOUR + FLIGHT'],['ABDOMEN + DEFENCE','The abdomen is protected by the elytra and can support chemical defence responses when threatened.','DEFENCE SYSTEM']]},
 {key:'housefly',name:'House Fly',latin:'Musca domestica',order:'Diptera',family:'Muscidae',range:'Worldwide',role:'Decomposer',diet:'Liquids / decaying matter',size:'6–7 mm',life:'15–30 days',color:0x9fb7be,card:'housefly.jpg',summary:'A rapid-lifecycle decomposer with halteres that stabilise flight and compound eyes for motion detection.',note:'Flies recycle organic matter and transfer nutrients through food webs.',anatomy:[['HEAD + COMPOUND EYES','Large compound eyes detect rapid changes in the visual field while antennae and mouthparts sample the environment.','SENSORY SYSTEM'],['WING + HALTERE','One functional wing pair drives flight; tiny halteres act as gyroscopic sensors for balance.','FLIGHT CONTROL'],['ABDOMEN','The segmented abdomen contains digestive and reproductive organs and supports the fly’s rapid lifecycle.','CORE BODY']]},
 {key:'cockroach',name:'Cockroach',latin:'Periplaneta americana',order:'Blattodea',family:'Blattidae',range:'Worldwide',role:'Decomposer',diet:'Omnivorous',size:'34–53 mm',life:'1–2 years',color:0x9a704e,card:'cockroach.jpg',summary:'A resilient detritivore built around a flexible exoskeleton, sensitive antennae and rapid locomotion.',note:'Cockroaches are resilient detritivores that participate in nutrient cycling.',anatomy:[['HEAD + ANTENNAE','Long antennae continuously sample chemical and tactile information around the animal.','SENSORY SYSTEM'],['THORAX + LEGS','The thorax anchors six powerful legs built for fast, low-profile movement across uneven surfaces.','LOCOMOTION'],['ABDOMEN + WINGS','The segmented abdomen protects internal organs; adult cockroaches may use their wings during movement.','CORE + FLIGHT']]},
 {key:'mosquito',name:'Mosquito',latin:'Aedes aegypti',order:'Diptera',family:'Culicidae',range:'Tropical + subtropical',role:'Pollinator / vector',diet:'Nectar / blood (female)',size:'3–6 mm',life:'~2–4 weeks',color:0x7182b6,card:'mosquito.jpg',summary:'A lightweight dipteran with a specialised proboscis and sensory antennae tuned to chemical cues.',note:'Mosquitoes occupy aquatic and terrestrial food webs; some species are important disease vectors.',anatomy:[['HEAD + ANTENNAE','Antennae and sensory palps detect odours, carbon dioxide and other cues that help locate hosts.','SENSORY SYSTEM'],['PROBOSCIS','The elongated mouthpart is specialised for piercing and feeding; females can take blood meals.','FEEDING SYSTEM'],['WINGS + ABDOMEN','A single wing pair provides flight while the abdomen expands to accommodate a blood meal and eggs.','FLIGHT + CORE']]}
];

const $=id=>document.getElementById(id);
const ui={
  preloader:$('preloader'),loadStage:$('loadStage'),loadPct:$('loadPct'),loadBar:$('loadBar'),canvas:$('mainCanvas'),
  title:$('specimenTitle'),latin:$('specimenLatin'),kicker:$('taxKicker'),no:$('specimenNo'),prev:$('prevMini'),next:$('nextMini'),cards:$('cards'),
  researchStep:$('researchStep'),researchTitle:$('researchTitle'),researchSub:$('researchSub'),researchStrip:$('researchStrip'),
  detail:$('detailHud'),detailTitle:$('detailTitle'),detailText:$('detailText'),detailMeta:$('detailMeta'),
  order:$('order'),family:$('family'),range:$('range'),role:$('role'),diet:$('diet'),size:$('size'),life:$('life'),summary:$('summary'),
  profile:$('profile'),sound:$('soundBtn'),stageHint:$('stageHint'),viewLabel:$('viewLabel')
};
let scene,camera,renderer,controls,loader,draco;
let lastTime=performance.now(),elapsed=0;
let index=0,research=0,autoRotate=true,soundOn=false,transitionLock=false;
let currentRig=null,currentModel=null,currentMixer=null;
let targetCam={z:4.65,y:.05,tx:0,ty:-.04};
const cache=new Map(),loading=new Map();
let sharedLogoTexture=null;
const viewStates=[
  {id:'01',title:'WHOLE SPECIMEN',sub:'Full specimen · default presentation',z:4.65,y:.05,tx:0,ty:-.03,scale:1},
  {id:'02',title:'HEAD / SENSORY SYSTEM',sub:'Macro view · head, eyes & antennae',z:3.15,y:.18,tx:0,ty:.34,scale:1.02},
  {id:'03',title:'CORE BODY / LOCOMOTION',sub:'Macro view · thorax, abdomen & movement',z:3.0,y:.05,tx:0,ty:.02,scale:1.05},
  {id:'04',title:'WINGS / FLIGHT SURFACE',sub:'Macro view · wings, elytra & flight structures',z:2.85,y:.22,tx:0,ty:.22,scale:1.08}
];
const audio={ctx:null,beep(type='click'){if(!soundOn)return;try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();this.ctx.resume();const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.connect(g);g.connect(this.ctx.destination);const t=this.ctx.currentTime;o.type='sine';o.frequency.setValueAtTime(type==='switch'?220:type==='pin'?720:520,t);o.frequency.exponentialRampToValueAtTime(type==='switch'?460:300,t+.09);g.gain.setValueAtTime(.022,t);g.gain.exponentialRampToValueAtTime(.001,t+.11);o.start(t);o.stop(t+.12);}catch{}}};
function setLoad(p,text){ui.loadPct.textContent=p+'%';ui.loadStage.textContent=text;ui.loadBar.style.width=p+'%';}
function pathFor(d){return `./models/${d.key==='mosquito'?'mosquito_3d_model_free':d.key}.glb`; }
function cloneScene(src){return SkeletonUtils.clone(src);}
function resize(){if(!renderer||!camera)return;const r=ui.canvas.parentElement.getBoundingClientRect();camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio||1,matchMedia('(max-width:820px)').matches?1.25:1.65));renderer.setSize(r.width,r.height,false);}
function initScene(){
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(32,1,.05,100);camera.position.set(0,.05,4.65);
 renderer=new THREE.WebGLRenderer({canvas:ui.canvas,alpha:true,antialias:true,powerPreference:'high-performance'});
 renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;
 renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 scene.add(new THREE.HemisphereLight(0xbfe9ff,0x05080d,1.15));
 const key=new THREE.DirectionalLight(0xffefcf,2.6);key.position.set(4.2,6.6,4.5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.near=.4;key.shadow.camera.far=20;key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.bias=-.00035;scene.add(key);
 const fill=new THREE.DirectionalLight(0x7bd7ff,1.45);fill.position.set(-5,2.8,3.6);scene.add(fill);
 const rim=new THREE.DirectionalLight(0xdff7ff,1.8);rim.position.set(-3.5,4.5,-5);scene.add(rim);
 const warm=new THREE.PointLight(0xffbd6a,1.0,8);warm.position.set(1.9,1.6,2.5);scene.add(warm);
 const lower=new THREE.SpotLight(0x66d9ff,0.65,8,Math.PI*.48,.65,1.5);lower.position.set(0,-.25,2.2);lower.target.position.set(0,.15,0);scene.add(lower,lower.target);
 loader=new GLTFLoader();draco=new DRACOLoader();draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/libs/draco/');draco.preload();loader.setDRACOLoader(draco);
 controls=new OrbitControls(camera,ui.canvas);controls.enablePan=false;controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=1.8;controls.maxDistance=5.8;controls.minPolarAngle=Math.PI*.29;controls.maxPolarAngle=Math.PI*.67;controls.target.set(0,-.03,0);
 window.addEventListener('resize',resize,{passive:true});window.visualViewport?.addEventListener('resize',resize,{passive:true});resize();
}
function tuneMaterials(root,key){root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if(!m)return;if(m.map)m.map.colorSpace=THREE.SRGBColorSpace;if(m.isMeshStandardMaterial||m.isMeshPhysicalMaterial){m.roughness=Math.max(.24,m.roughness??.5);m.metalness=Math.min(.2,m.metalness??0);}m.needsUpdate=true;});});}
function normalize(root,key){root.position.set(0,0,0);root.rotation.set(0,0,0);root.scale.setScalar(1);const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3());const target={butterfly:3.15,bee:2.75,ant:2.6,dragonfly:3.35,ladybug:2.7,housefly:2.95,cockroach:3.05,mosquito:3.1}[key]||2.9;const k=target/(Math.max(size.x,size.y,size.z)||1);root.scale.setScalar(k);root.userData.speciesKey=key;return root;}
function safeClips(animations){return (animations||[]).map(c=>{const tracks=(c.tracks||[]).filter(t=>t&&typeof t.createInterpolant==='function'&&t.times?.length&&t.values?.length);return tracks.length?new THREE.AnimationClip(c.name||'specimen',c.duration,tracks):null;}).filter(Boolean);}
function collectMotionNodes(root,key){const list=[];root.traverse(o=>{const n=(o.name||'').toLowerCase();let wing=/wing|wings|forewing|hindwing|wingroot|ala/.test(n);if(key==='dragonfly'&&/^plane\.00[1-4]/.test(n))wing=true;if(key==='butterfly'&&/^butterfly\./.test(n))wing=true;if(key==='mosquito'&&/wing|backwing|fmid wing|front wing|wing bottom/.test(n))wing=true;if(key==='housefly'&&/wing/.test(n))wing=true;if(wing)list.push({o,baseZ:o.rotation.z,baseX:o.rotation.x,phase:list.length*.73});});return list;}
function setupMotion(root,d){currentMixer=null;const clips=safeClips(root.userData.animations||[]);if(clips.length){try{currentMixer=new THREE.AnimationMixer(root);for(const clip of clips){const action=currentMixer.clipAction(clip);action.reset().play();}}catch(err){console.warn('Animation clips skipped for',d.key,err);currentMixer=null;}}root.userData.motionNodes=collectMotionNodes(root,d.key);}
function buildFloatingStage(d){
 const rig=new THREE.Group();rig.name='SpecimenRig';
 const stage=new THREE.Group();stage.position.y=-.66;
 const lower=new THREE.Mesh(new THREE.CylinderGeometry(1.22,1.34,.16,72),new THREE.MeshStandardMaterial({color:0x0b1118,metalness:.82,roughness:.25}));lower.castShadow=true;lower.receiveShadow=true;stage.add(lower);
 const plate=new THREE.Mesh(new THREE.CylinderGeometry(1.08,1.14,.065,72),new THREE.MeshStandardMaterial({color:0x18212b,metalness:.72,roughness:.24}));plate.position.y=.11;plate.receiveShadow=true;stage.add(plate);
 const ring=new THREE.Mesh(new THREE.TorusGeometry(.96,.03,16,72),new THREE.MeshStandardMaterial({color:0x78ddff,emissive:0x299bc6,emissiveIntensity:.8,metalness:.35,roughness:.18}));ring.rotation.x=Math.PI/2;ring.position.y=.155;stage.add(ring);
 const inner=new THREE.Mesh(new THREE.TorusGeometry(.78,.012,10,72),new THREE.MeshStandardMaterial({color:0xe6bd6d,emissive:0x6b4b1c,emissiveIntensity:.35,metalness:.55,roughness:.22}));inner.rotation.x=Math.PI/2;inner.position.y=.158;stage.add(inner);
 const logoMat=sharedLogoTexture?new THREE.MeshBasicMaterial({map:sharedLogoTexture,transparent:true,opacity:.92,depthWrite:false}):new THREE.MeshBasicMaterial({color:0x8bdfff});
 const logo=new THREE.Mesh(new THREE.CircleGeometry(.30,64),logoMat);logo.rotation.x=-Math.PI/2;logo.position.y=.162;stage.add(logo);
 const halo=new THREE.Mesh(new THREE.CircleGeometry(.88,64),new THREE.MeshBasicMaterial({color:0x49cfff,transparent:true,opacity:.075,depthWrite:false,blending:THREE.AdditiveBlending}));halo.rotation.x=-Math.PI/2;halo.position.y=.164;stage.add(halo);
 const glow=new THREE.PointLight(d.color,.36,3.0);glow.position.set(0,.3,0.1);stage.add(glow);
 rig.add(stage);
 const box=new THREE.Box3().setFromObject(root);const desiredY=.02;root.position.y += desiredY-box.min.y;rig.add(root);
 rig.userData.stage=stage;rig.userData.model=root;return rig;
}
function currentRigMotion(t){if(!currentRig)return;currentRig.position.y=Math.sin(t*.00115)*.018;currentRig.rotation.z=Math.sin(t*.0006)*.006;if(autoRotate)currentRig.rotation.y+=.0022;const nodes=currentModel?.userData.motionNodes||[];for(const n of nodes){const key=currentModel?.userData.speciesKey;let amp=.04,f=.014;if(key==='dragonfly')amp=.13,f=.020;if(key==='butterfly')amp=.09,f=.015;if(key==='bee')amp=.08,f=.016;if(key==='mosquito')amp=.09,f=.019;if(key==='housefly')amp=.10,f=.018;n.o.rotation.z=n.baseZ+Math.sin(t*f+n.phase)*amp;n.o.rotation.x=n.baseX+Math.cos(t*f+n.phase)*amp*.14;}}
async function loadModel(d,critical=false){if(cache.has(d.key))return cloneScene(cache.get(d.key));if(loading.has(d.key))return cloneScene(await loading.get(d.key));const p=new Promise((resolve,reject)=>loader.load(pathFor(d),g=>resolve(g),e=>{if(critical&&e.total){const pct=Math.min(72,18+Math.round(e.loaded/e.total*54));setLoad(pct,`DECODING ${d.name.toUpperCase()}`);}},reject)).then(g=>{g.scene.userData.animations=g.animations||[];tuneMaterials(g.scene,d.key);normalize(g.scene,d.key);cache.set(d.key,g.scene);return g.scene;});loading.set(d.key,p);try{return cloneScene(await p);}finally{loading.delete(d.key);}}
function updateUI(d){ui.title.textContent=d.name;ui.latin.textContent=d.latin;ui.kicker.textContent=`${d.order.toUpperCase()} // ${d.family.toUpperCase()}`;ui.no.textContent=String(index+1).padStart(2,'0');ui.prev.textContent=DATA[(index+7)%8].name;ui.next.textContent=DATA[(index+1)%8].name;ui.order.textContent=d.order;ui.family.textContent=d.family;ui.range.textContent=d.range;ui.role.textContent=d.role;ui.diet.textContent=d.diet;ui.size.textContent=d.size;ui.life.textContent=d.life;ui.summary.textContent=d.summary;document.documentElement.style.setProperty('--accent',`#${d.color.toString(16).padStart(6,'0')}`);ui.stageHint.textContent=`${String(index+1).padStart(2,'0')} / 08  ·  SWIPE OR SELECT A SPECIMEN`;ui.viewLabel.textContent=viewStates[research].id;}
function renderCards(){ui.cards.innerHTML='';DATA.forEach((d,i)=>{let rel=((i-index+4)%8)-4;const angle=rel*18;const rad=angle*Math.PI/180;const x=Math.sin(rad)*330;const y=(1-Math.cos(rad))*62;const scale=rel===0?1.14:Math.max(.68,1-Math.abs(rel)*.09);const op=rel===0?1:Math.max(.28,.92-Math.abs(rel)*.14);const z=10-Math.abs(rel);const b=document.createElement('button');b.className='specimen-card'+(rel===0?' is-active':'');b.type='button';b.dataset.rel=rel;b.style.cssText=`--x:${x}px;--y:${y}px;--scale:${scale};--rot:${angle*.20}deg;--ry:${-angle}deg;--op:${op};--z:${z};`;b.innerHTML=`<img src="./assets/cards/${d.card}" alt="${d.name}" loading="lazy"><span class="card-gloss"></span><span class="card-number">${String(i+1).padStart(2,'0')}</span><span class="card-name">${d.name}</span><span class="card-latin">${d.latin}</span>${rel===0?'<span class="card-active">ACTIVE</span>':''}`;b.addEventListener('click',()=>switchTo(i));ui.cards.appendChild(b);});}
function applyResearch(show=true){const d=DATA[index],v=viewStates[research];ui.researchStep.textContent=v.id;ui.researchTitle.textContent=v.title;ui.researchSub.textContent=research===3?d.anatomy[1][0]:v.sub;ui.viewLabel.textContent=v.id;targetCam={z:v.z,y:v.y,tx:v.tx,ty:v.ty};if(currentRig)currentRig.scale.setScalar(v.scale);if(research===0){closeDetail();}else{openDetail(research-1,false);}document.body.dataset.research=String(research+1);if(show){ui.researchStrip.classList.add('show');clearTimeout(window.__rs);window.__rs=setTimeout(()=>ui.researchStrip.classList.remove('show'),1200);}}
function stepResearch(dir){const next=THREE.MathUtils.clamp(research+dir,0,3);if(next===research)return;research=next;applyResearch(true);audio.beep('click');}
function openDetail(i,sound=true){const d=DATA[index],a=d.anatomy[i%3];ui.detailTitle.textContent=a[0];ui.detailText.textContent=a[1];ui.detailMeta.textContent=a[2];ui.detail.dataset.open='1';if(sound)audio.beep('pin');}
function closeDetail(){ui.detail.dataset.open='0';}
function switchTo(next){if(transitionLock)return;const target=(next+8)%8;if(target===index){return;}transitionLock=true;const old=currentRig;const dir=((target-index+8)%8)<=4?1:-1;index=target;research=0;const d=DATA[index];updateUI(d);renderCards();applyResearch(false);audio.beep('switch');
 const finish=root=>{setupMotion(root,d);const rig=buildFloatingStage(d);rig.position.x=dir*.7;rig.rotation.y=dir*.28;rig.scale.setScalar(.92);scene.add(rig);currentRig=rig;currentModel=root;const start=performance.now();function reveal(){const p=Math.min(1,(performance.now()-start)/620),e=1-Math.pow(1-p,3);if(currentRig!==rig)return;rig.position.x=THREE.MathUtils.lerp(dir*.7,0,e);rig.rotation.y=THREE.MathUtils.lerp(dir*.28,0,e);rig.scale.setScalar(THREE.MathUtils.lerp(.92,1,e));if(p<1)requestAnimationFrame(reveal);else{if(old)scene.remove(old);transitionLock=false;preloadNeighbors();}}requestAnimationFrame(reveal);};
 if(cache.has(d.key))finish(cloneScene(cache.get(d.key)));else loadModel(d,true).then(finish).catch(err=>{console.error('Specimen load failed',err);transitionLock=false;});}
function preloadNeighbors(){const ids=[(index+1)%8,(index+7)%8,(index+2)%8,(index+6)%8];const run=async()=>{for(const id of ids){const d=DATA[id];if(!cache.has(d.key))try{await loadModel(d)}catch(err){console.warn('Preload failed',d.key,err);}}};(window.requestIdleCallback||((fn)=>setTimeout(fn,350)))(run);}
async function boot(){try{initScene();setLoad(8,'INITIALISING 3D ENGINE');try{sharedLogoTexture=await new THREE.TextureLoader().loadAsync('./assets/logo.png');sharedLogoTexture.colorSpace=THREE.SRGBColorSpace;}catch{}setLoad(16,'PRELOADING PRIMARY SPECIMEN');const primaryPromise=loadModel(DATA[0],true);const neighborPromise=Promise.all([loadModel(DATA[7]),loadModel(DATA[1])]);const [primary]=await Promise.all([primaryPromise,neighborPromise]);setLoad(76,'BUILDING FLOATING SPECIMEN STAGE');setupMotion(primary,DATA[0]);currentModel=primary;currentRig=buildFloatingStage(DATA[0]);scene.add(currentRig);updateUI(DATA[0]);renderCards();applyResearch(false);setLoad(94,'OPTICAL CALIBRATION');await new Promise(r=>setTimeout(r,180));setLoad(100,'CATALOGUE READY');setTimeout(()=>ui.preloader.classList.add('hidden'),260);preloadNeighbors();animate();}catch(err){console.error('BOOT FAILED',err);setLoad(100,'3D OFFLINE — RETRYING');setTimeout(()=>ui.preloader.classList.add('hidden'),700);if(!scene)initScene();renderCards();animate();}}
function setupEvents(){
 $('prevBtn').addEventListener('click',()=>switchTo(index-1));$('nextBtn').addEventListener('click',()=>switchTo(index+1));$('cardLeft').addEventListener('click',()=>switchTo(index-1));$('cardRight').addEventListener('click',()=>switchTo(index+1));
 $('autoBtn').addEventListener('click',e=>{autoRotate=!autoRotate;e.currentTarget.querySelector('span').textContent=autoRotate?'ON':'OFF';});
 $('resetBtn').addEventListener('click',()=>{research=0;applyResearch(false);controls.target.set(0,-.03,0);camera.position.set(0,.05,4.65);if(currentRig){currentRig.scale.setScalar(1);currentRig.position.x=0;currentRig.rotation.set(0,0,0);}});
 ui.sound.addEventListener('click',()=>{soundOn=!soundOn;ui.sound.textContent=soundOn?'SOUND ON':'SOUND OFF';ui.sound.classList.toggle('on',soundOn);audio.beep('click');});$('closeDetail').addEventListener('click',closeDetail);
 window.addEventListener('keydown',e=>{if(e.key==='ArrowRight')switchTo(index+1);else if(e.key==='ArrowLeft')switchTo(index-1);else if(e.key==='ArrowDown')stepResearch(1);else if(e.key==='ArrowUp')stepResearch(-1);else if(e.key==='Escape')closeDetail();});
 let sx=0,sy=0,activePointer=false;ui.canvas.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;activePointer=true;},{passive:true});ui.canvas.addEventListener('pointerup',e=>{if(!activePointer)return;activePointer=false;const dx=e.clientX-sx,dy=e.clientY-sy;sx=sy=0;if(Math.max(Math.abs(dx),Math.abs(dy))>48){if(Math.abs(dx)>Math.abs(dy))switchTo(index+(dx<0?1:-1));else stepResearch(dy>0?1:-1);return;}if(e.pointerType==='touch'||transitionLock||!currentModel)return;const r=ui.canvas.getBoundingClientRect(),p=new THREE.Vector2(((e.clientX-r.left)/r.width)*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(p,camera);const hit=ray.intersectObject(currentModel,true)[0];if(!hit)return;const box=new THREE.Box3().setFromObject(currentModel),local=currentModel.worldToLocal(hit.point.clone());const h=(local.y-box.min.y)/(box.max.y-box.min.y||1);let part=h>.68?0:h<.34?2:1;if(Math.abs(local.x)>Math.max(.45,(box.max.x-box.min.x)*.22))part=1;openDetail(part,true);});
 const v=$('viewer');v.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<12||e.ctrlKey)return;e.preventDefault();stepResearch(e.deltaY>0?1:-1);},{passive:false});
 ui.cards.addEventListener('pointerdown',e=>{ui.cards.dataset.sx=e.clientX});ui.cards.addEventListener('pointerup',e=>{const dx=e.clientX-Number(ui.cards.dataset.sx||e.clientX);if(Math.abs(dx)>48)switchTo(index+(dx<0?1:-1));});
}
function animate(){requestAnimationFrame(animate);const now=performance.now();const delta=Math.min(.05,(now-lastTime)/1000);lastTime=now;elapsed+=delta;controls?.update();if(currentMixer)currentMixer.update(delta);currentRigMotion(now);camera.position.z=THREE.MathUtils.damp(camera.position.z,targetCam.z,5,delta);camera.position.y=THREE.MathUtils.damp(camera.position.y,targetCam.y,5,delta);controls?.target.lerp(new THREE.Vector3(targetCam.tx,targetCam.ty,0),Math.min(1,delta*5));if(renderer&&scene&&camera)renderer.render(scene,camera);}
setupEvents();boot();
