import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/loaders/DRACOLoader.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/controls/OrbitControls.js';
import * as SkeletonUtils from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/utils/SkeletonUtils.js';

const DATA = [
 {key:'butterfly',name:'Butterfly',latin:'Danaus plexippus',order:'Lepidoptera',family:'Nymphalidae',range:'Worldwide',role:'Pollinator',diet:'Nectar',size:'8.5–10.5 cm',life:'2–6 weeks adult',color:0xffa63d,card:'butterfly.jpg',summary:'A pollinator whose wing scales create visual signalling, camouflage and thermoregulation.',note:'Pollination, food webs and seasonal migration make butterflies valuable ecological indicators.',anatomy:[['HEAD + ANTENNAE','Sensory antennae and compound eyes orient the butterfly toward odours, movement and light.','SENSORY SYSTEM'],['WING SURFACE','Microscopic wing scales scatter light and contribute to colour, signalling and camouflage.','FLIGHT SURFACE'],['THORAX + ABDOMEN','Flight muscles sit in the thorax while the abdomen contains major digestive and reproductive organs.','CORE BODY']]},
 {key:'bee',name:'Honey Bee',latin:'Apis mellifera',order:'Hymenoptera',family:'Apidae',range:'Worldwide',role:'Pollinator',diet:'Nectar + pollen',size:'12–15 mm',life:'~6 weeks worker',color:0xf1b84b,card:'bee.jpg',summary:'A social pollinator with a specialised pollen basket and complex colony communication.',note:'Bees support flowering plant reproduction and form tightly coordinated social colonies.',anatomy:[['HEAD + EYES','Compound eyes detect motion and colour while antennae provide chemical and tactile information.','SENSORY SYSTEM'],['WINGS + FLIGHT MUSCLES','Two pairs of wings are coupled in flight; rapid wing beats support hovering and precise navigation.','FLIGHT SYSTEM'],['ABDOMEN + STINGER','The abdomen houses digestive and reproductive organs; workers have a defensive stinger.','DEFENCE + CORE']]},
 {key:'ant',name:'Ant',latin:'Formica rufa',order:'Hymenoptera',family:'Formicidae',range:'Europe + Asia',role:'Soil engineer',diet:'Omnivorous',size:'4–9 mm',life:'Weeks–years',color:0xb46d45,card:'ant.jpg',summary:'A colony-driven soil engineer with extreme cooperative behaviour and specialised caste roles.',note:'Ants aerate soil, redistribute nutrients and help shape microhabitats.',anatomy:[['HEAD + MANDIBLES','The head carries sensory antennae and powerful mandibles used for feeding, defence and carrying.','SENSORY + TOOLS'],['THORAX + LEGS','The thorax anchors six jointed legs that provide traction and rapid ground locomotion.','LOCOMOTION'],['ABDOMEN','The abdomen contains major internal organs and chemical communication structures used by the colony.','CORE BODY']]},
 {key:'dragonfly',name:'Dragonfly',latin:'Anax imperator',order:'Odonata',family:'Aeshnidae',range:'Africa + Eurasia',role:'Predator',diet:'Predatory insects',size:'66–84 mm',life:'Weeks–months adult',color:0x54bdc4,card:'dragonfly.jpg',summary:'A precision aerial predator with independent wing control and exceptional visual acuity.',note:'Dragonflies are efficient aerial predators and useful signals of freshwater ecosystem health.',anatomy:[['HEAD + COMPOUND EYES','Huge compound eyes provide a wide visual field for tracking prey during aerial pursuit.','VISION SYSTEM'],['FOUR WINGS','Each wing can contribute independently to lift, braking and manoeuvring for precise aerial control.','FLIGHT SYSTEM'],['ABDOMEN','The long abdomen balances the body in flight and carries respiratory, digestive and reproductive systems.','CORE BODY']]},
 {key:'ladybug',name:'Ladybird',latin:'Coccinella septempunctata',order:'Coleoptera',family:'Coccinellidae',range:'Northern Hemisphere',role:'Biocontrol',diet:'Aphids',size:'5–8 mm',life:'1 year',color:0xe14f48,card:'ladybug.jpg',summary:'A compact beetle whose warning colours advertise chemical defences to predators.',note:'Ladybirds help regulate aphid populations and can protect crops naturally.',anatomy:[['HEAD + ANTENNAE','The small head carries compound eyes and short antennae that help locate prey and environmental cues.','SENSORY SYSTEM'],['ELYTRA + WINGS','The coloured wing covers protect folded flight wings beneath the hard beetle shell.','ARMOUR + FLIGHT'],['ABDOMEN + DEFENCE','The abdomen is protected by the elytra and can support chemical defence responses when threatened.','DEFENCE SYSTEM']]},
 {key:'housefly',name:'House Fly',latin:'Musca domestica',order:'Diptera',family:'Muscidae',range:'Worldwide',role:'Decomposer',diet:'Liquids / decaying matter',size:'6–7 mm',life:'15–30 days',color:0x9fb7be,card:'housefly.jpg',summary:'A rapid-lifecycle decomposer with halteres that stabilise flight and compound eyes for motion detection.',note:'Flies recycle organic matter and transfer nutrients through food webs.',anatomy:[['HEAD + COMPOUND EYES','Large compound eyes detect rapid changes in the visual field while antennae and mouthparts sample the environment.','SENSORY SYSTEM'],['WING + HALTERE','One functional wing pair drives flight; tiny halteres act as gyroscopic sensors for balance.','FLIGHT CONTROL'],['ABDOMEN','The segmented abdomen contains digestive and reproductive organs and supports the fly’s rapid lifecycle.','CORE BODY']]},
 {key:'cockroach',name:'Cockroach',latin:'Periplaneta americana',order:'Blattodea',family:'Blattidae',range:'Worldwide',role:'Decomposer',diet:'Omnivorous',size:'34–53 mm',life:'1–2 years',color:0x9a704e,card:'cockroach.jpg',summary:'A resilient detritivore built around a flexible exoskeleton, sensitive antennae and rapid locomotion.',note:'Cockroaches are resilient detritivores that participate in nutrient cycling.',anatomy:[['HEAD + ANTENNAE','Long antennae continuously sample chemical and tactile information around the animal.','SENSORY SYSTEM'],['THORAX + LEGS','The thorax anchors six powerful legs built for fast, low-profile movement across uneven surfaces.','LOCOMOTION'],['ABDOMEN + WINGS','The segmented abdomen protects internal organs; adult cockroaches may use their wings during movement.','CORE + FLIGHT']]},
 {key:'mosquito',name:'Mosquito',latin:'Aedes aegypti',order:'Diptera',family:'Culicidae',range:'Tropical + subtropical',role:'Pollinator / vector',diet:'Nectar / blood (female)',size:'3–6 mm',life:'~2–4 weeks',color:0x7182b6,card:'mosquito.jpg',summary:'A lightweight dipteran with a specialised proboscis and sensory antennae tuned to chemical cues.',note:'Mosquitoes occupy aquatic and terrestrial food webs; some species are important disease vectors.',anatomy:[['HEAD + ANTENNAE','Antennae and sensory palps detect odours, carbon dioxide and other cues that help locate hosts.','SENSORY SYSTEM'],['PROBOSCIS','The elongated mouthpart is specialised for piercing and feeding; females can take blood meals.','FEEDING SYSTEM'],['WINGS + ABDOMEN','A single wing pair provides flight while the abdomen expands to accommodate a blood meal and eggs.','FLIGHT + CORE']]}
];

const $=id=>document.getElementById(id);
const ui={preloader:$('preloader'),loadStage:$('loadStage'),loadPct:$('loadPct'),loadBar:$('loadBar'),canvas:$('mainCanvas'),title:$('specimenTitle'),latin:$('specimenLatin'),kicker:$('taxKicker'),no:$('specimenNo'),prev:$('prevMini'),next:$('nextMini'),cards:$('cards'),researchStrip:$('researchStrip'),researchStep:$('researchStep'),researchTitle:$('researchTitle'),researchSub:$('researchSub'),detail:$('detailHud'),detailTitle:$('detailTitle'),detailText:$('detailText'),detailMeta:$('detailMeta'),order:$('order'),family:$('family'),range:$('range'),role:$('role'),diet:$('diet'),size:$('size'),life:$('life'),summary:$('summary'),profile:$('profile'),clock:$('clock'),sound:$('soundBtn')};
let scene,camera,renderer,controls,loader,draco,model=null,mixer=null,clock3=new THREE.Clock();
let index=0,research=0,autoRotate=true,soundOn=false,transitionLock=false;
let targetCam={z:4.15,y:.18,ty:.02};
const cache=new Map(); const loading=new Map();

const audio={ctx:null,beep(type='click'){if(!soundOn)return;try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();this.ctx.resume();const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.connect(g);g.connect(this.ctx.destination);const t=this.ctx.currentTime;o.type='sine';o.frequency.setValueAtTime(type==='switch'?240:type==='pin'?740:560,t);o.frequency.exponentialRampToValueAtTime(type==='switch'?520:330,t+.09);g.gain.setValueAtTime(.04,t);g.gain.exponentialRampToValueAtTime(.001,t+.11);o.start(t);o.stop(t+.12);}catch{}}};

function setLoad(p,text){ui.loadPct.textContent=p+'%';ui.loadStage.textContent=text;ui.loadBar.style.width=p+'%';}
function clock(){ui.clock.textContent=new Date().toLocaleTimeString([], {hour12:false});}
function pathFor(d){return `./models/${d.key==='mosquito'?'mosquito_3d_model_free':d.key}.glb`;}
function cloneScene(src){return SkeletonUtils.clone(src);}
function resize(){if(!renderer||!camera)return;const r=ui.canvas.parentElement.getBoundingClientRect();camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio||1,matchMedia('(max-width:820px)').matches?1.35:1.6));renderer.setSize(r.width,r.height,false);}

function initScene(){
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(29,1,.05,100);camera.position.set(0,.18,4.15);
 renderer=new THREE.WebGLRenderer({canvas:ui.canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 scene.add(new THREE.HemisphereLight(0x9fdfff,0x03060a,1.45));
 const key=new THREE.DirectionalLight(0xd5efff,3.1);key.position.set(-3,4.6,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.camera.far=16;scene.add(key);
 const fill=new THREE.PointLight(0x3f98ff,14,7);fill.position.set(3,1.2,3);scene.add(fill);
 const warm=new THREE.PointLight(0xff9c62,5,6);warm.position.set(-2,-.2,2.5);scene.add(warm);
 const rim=new THREE.SpotLight(0x66e0ff,13,9,Math.PI/5,.55,1);rim.position.set(0,3.5,-2.5);rim.target.position.set(0,.1,0);scene.add(rim,rim.target);
 const base=new THREE.Group();
 const disk=new THREE.Mesh(new THREE.CylinderGeometry(1.3,.98,.12,96),new THREE.MeshStandardMaterial({color:0x1a2430,metalness:.82,roughness:.28,emissive:0x06111b,emissiveIntensity:.6}));disk.position.y=-.72;disk.receiveShadow=true;base.add(disk);
 const rimMesh=new THREE.Mesh(new THREE.TorusGeometry(1.2,.035,14,96),new THREE.MeshStandardMaterial({color:0x6adfff,metalness:.7,roughness:.2,emissive:0x0b7495,emissiveIntensity:1.5}));rimMesh.rotation.x=Math.PI/2;rimMesh.position.y=-.64;base.add(rimMesh);
 const tex=new THREE.TextureLoader().load('./assets/logo.png');tex.colorSpace=THREE.SRGBColorSpace;const logo=new THREE.Mesh(new THREE.CircleGeometry(.52,64),new THREE.MeshBasicMaterial({map:tex,transparent:true,opacity:.8,depthWrite:false}));logo.rotation.x=-Math.PI/2;logo.position.y=-.64;base.add(logo);
 const under=new THREE.PointLight(0x38d9ff,10,3.8);under.position.set(0,-.45,.15);base.add(under);scene.add(base);
 controls=new OrbitControls(camera,ui.canvas);controls.enablePan=false;controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=2.65;controls.maxDistance=5.2;controls.minPolarAngle=Math.PI*.34;controls.maxPolarAngle=Math.PI*.61;controls.target.set(0,.02,0);
 loader=new GLTFLoader();draco=new DRACOLoader();draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/libs/draco/');draco.preload();loader.setDRACOLoader(draco);
 window.addEventListener('resize',resize,{passive:true});window.visualViewport?.addEventListener('resize',resize,{passive:true});resize();
}

function tuneMaterials(root,key){root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if(!m)return;if(m.map)m.map.colorSpace=THREE.SRGBColorSpace;if(key==='bee'&&m.map)m.color.set(0xffffff);if(m.isMeshStandardMaterial||m.isMeshPhysicalMaterial){m.roughness=Math.max(.32,m.roughness??.5);m.metalness=Math.min(.22,m.metalness??0);}m.needsUpdate=true;});});}
function normalize(root,key){const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());root.position.sub(center);root.position.y+=.08;const target={butterfly:2.18,bee:1.72,ant:1.7,dragonfly:2.4,ladybug:1.7,housefly:1.85,cockroach:1.95,mosquito:2.05}[key]||1.9;const k=target/(Math.max(size.x,size.y,size.z)||1);root.scale.setScalar(k);root.userData.speciesKey=key;return root;}
async function loadModel(d,critical=false){if(cache.has(d.key))return cloneScene(cache.get(d.key));if(loading.has(d.key))return cloneScene(await loading.get(d.key));const p=new Promise((resolve,reject)=>loader.load(pathFor(d),g=>resolve(g),e=>{if(critical&&e.total)setLoad(Math.min(84,25+Math.round(e.loaded/e.total*59)),`DECODING ${d.name.toUpperCase()}`);},reject)).then(g=>{g.scene.userData.animations=g.animations||[];tuneMaterials(g.scene,d.key);normalize(g.scene,d.key);cache.set(d.key,g.scene);return g.scene;});loading.set(d.key,p);try{return cloneScene(await p);}finally{loading.delete(d.key);}}

function setupMotion(root,d){mixer=null;const animations=root.userData.animations||[];if(animations.length){mixer=new THREE.AnimationMixer(root);animations.forEach(c=>mixer.clipAction(c).play());}const wings=[];root.traverse(o=>{const n=(o.name||'').toLowerCase();if(/wing|ala|forewing|hindwing|wings/.test(n))wings.push({o,base:o.rotation.z,phase:wings.length*.7});});root.userData.wings=wings;}
function removeOld(old){if(!old)return;scene.remove(old);}

function switchTo(next){if(transitionLock)return;const target=(next+DATA.length)%DATA.length;if(target===index)return;transitionLock=true;const dir=((target-index+8)%8)<=4?1:-1;const d=DATA[target];index=target;updateUI(d);renderCards();research=0;applyResearch(false);audio.beep('switch');const old=model;const finish=root=>{root.userData.speciesKey=d.key;tuneMaterials(root,d.key);setupMotion(root,d);root.position.x=dir*.24;root.rotation.y=dir*.18;scene.add(root);model=root;const start=performance.now();function reveal(){const p=Math.min(1,(performance.now()-start)/580),e=1-Math.pow(1-p,3);if(model===root){root.position.x=THREE.MathUtils.lerp(dir*.24,0,e);root.rotation.y=THREE.MathUtils.lerp(dir*.18,0,e);}if(p<1)requestAnimationFrame(reveal);else{removeOld(old);transitionLock=false;}}reveal();preloadNeighbors();};if(cache.has(d.key))finish(cloneScene(cache.get(d.key)));else loadModel(d,true).then(finish).catch(()=>{transitionLock=false});}
function preloadNeighbors(){const ids=[(index+1)%8,(index+7)%8,(index+2)%8,(index+6)%8];let cursor=0;const run=async()=>{for(;cursor<ids.length;cursor++){const d=DATA[ids[cursor]];if(!cache.has(d.key))try{await loadModel(d)}catch{}}};(window.requestIdleCallback?requestIdleCallback:fn=>setTimeout(fn,900))(run);}

function updateUI(d){ui.title.textContent=d.name;ui.latin.textContent=d.latin;ui.kicker.textContent=`${d.order.toUpperCase()} // ${d.family.toUpperCase()}`;ui.no.textContent=String(index+1).padStart(2,'0');ui.prev.textContent=DATA[(index+7)%8].name;ui.next.textContent=DATA[(index+1)%8].name;ui.order.textContent=d.order;ui.family.textContent=d.family;ui.range.textContent=d.range;ui.role.textContent=d.role;ui.diet.textContent=d.diet;ui.size.textContent=d.size;ui.life.textContent=d.life;ui.summary.textContent=d.summary;document.documentElement.style.setProperty('--accent',`#${d.color.toString(16).padStart(6,'0')}`);}
function renderCards(){ui.cards.innerHTML='';DATA.forEach((d,i)=>{const rel=((i-index+4+8)%8)-4;const abs=Math.abs(rel);const b=document.createElement('button');b.className='specimen-card';b.dataset.rel=rel;b.type='button';const x=rel*122;const y=abs*4;const scale=Math.max(.62,1-abs*.1);const rot=rel*-4;const ry=rel*-18;const op=Math.max(.46,1-abs*.12);const xm=rel*88;b.style.cssText=`--x:${x}px;--xm:${xm}px;--y:${y}px;--scale:${scale};--rot:${rot}deg;--ry:${ry}deg;--op:${op};`;b.innerHTML=`<img src="./assets/cards/${d.card}" alt="${d.name} specimen illustration"><div class="card-shade"></div><span class="card-number">${String(i+1).padStart(2,'0')}</span><div class="card-info"><strong>${d.name}</strong><small>${d.latin}</small></div>${rel===0?'<span class="active-tag">ACTIVE</span>':''}`;b.addEventListener('click',()=>switchTo(i));ui.cards.appendChild(b);});}

function applyResearch(show=true){const d=DATA[index];document.body.dataset.research=String(research+1);const states=[['01','WHOLE SPECIMEN','Observe silhouette, movement and surface.'],['02','ANATOMY / MACRO','Move closer to a key anatomical region.'],['03','ECOLOGY / FIELD NOTE',d.note]];const [step,title,sub]=states[research];ui.researchStep.textContent=step;ui.researchTitle.textContent=title;ui.researchSub.textContent=sub;if(research===0){targetCam={z:4.15,y:.18,ty:.02};closeDetail()}else if(research===1){targetCam={z:3.08,y:.24,ty:.13};openDetail(1,false)}else{targetCam={z:4.55,y:.42,ty:-.04};openDetail(2,false)}if(show){ui.researchStrip.classList.add('show');clearTimeout(window.__rs);window.__rs=setTimeout(()=>ui.researchStrip.classList.remove('show'),1700);}}
function stepResearch(dir){research=(research+dir+3)%3;applyResearch(true);audio.beep('click');}
function openDetail(i,sound=true){const a=DATA[index].anatomy[i%3];ui.detailTitle.textContent=a[0];ui.detailText.textContent=a[1];ui.detailMeta.textContent=a[2];ui.detail.dataset.open='1';if(sound)audio.beep('pin');}
function closeDetail(){ui.detail.removeAttribute('data-open');}

function bind(){
 $('prevBtn').addEventListener('click',()=>switchTo(index-1));$('nextBtn').addEventListener('click',()=>switchTo(index+1));$('cardLeft').addEventListener('click',()=>switchTo(index-1));$('cardRight').addEventListener('click',()=>switchTo(index+1));
 $('autoBtn').addEventListener('click',e=>{autoRotate=!autoRotate;e.currentTarget.classList.toggle('on',autoRotate);e.currentTarget.querySelector('span').textContent=autoRotate?'ON':'OFF';});
 $('resetBtn').addEventListener('click',()=>{camera.position.set(0,.18,4.15);controls.target.set(0,.02,0);controls.update();research=0;applyResearch(false);});
 $('expandBtn').addEventListener('click',()=>ui.profile.classList.toggle('expanded'));ui.sound.addEventListener('click',()=>{soundOn=!soundOn;ui.sound.textContent=soundOn?'SOUND ON':'SOUND OFF';ui.sound.classList.toggle('on',soundOn);audio.beep('click');});
 $('closeDetail').addEventListener('click',closeDetail);
 window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')switchTo(index-1);else if(e.key==='ArrowRight')switchTo(index+1);else if(e.key==='ArrowDown')stepResearch(1);else if(e.key==='ArrowUp')stepResearch(-1);else if(e.key==='Escape')closeDetail();});
 let sx=0,sy=0,st=0;const v=$('viewer');v.addEventListener('wheel',e=>{if(e.ctrlKey||Math.abs(e.deltaY)<12)return;e.preventDefault();stepResearch(e.deltaY>0?1:-1);},{passive:false});v.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;sx=e.clientX;sy=e.clientY;st=performance.now();},{passive:true});v.addEventListener('pointerup',e=>{if(!sx)return;const dx=e.clientX-sx,dy=e.clientY-sy;const dur=performance.now()-st;sx=sy=0;if(dur<900&&Math.max(Math.abs(dx),Math.abs(dy))>45){if(Math.abs(dx)>Math.abs(dy))switchTo(index+(dx<0?1:-1));else stepResearch(dy>0?1:-1);}});
 let cs=0;ui.cards.addEventListener('pointerdown',e=>{cs=e.clientX});ui.cards.addEventListener('pointerup',e=>{const dx=e.clientX-cs;if(Math.abs(dx)>45)switchTo(index+(dx<0?1:-1));});
 const ray=new THREE.Raycaster(),p=new THREE.Vector2();ui.canvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch'||!model)return;const r=ui.canvas.getBoundingClientRect();p.x=((e.clientX-r.left)/r.width)*2-1;p.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(p,camera);const hit=ray.intersectObject(model,true)[0];if(!hit)return;const local=model.worldToLocal(hit.point.clone());const box=new THREE.Box3().setFromObject(model);const n=THREE.MathUtils.clamp((local.y-box.min.y)/(box.max.y-box.min.y||1),0,1);openDetail(n>.68?0:n<.35?2:1);});
}

function tick(){requestAnimationFrame(tick);const dt=Math.min(clock3.getDelta(),.05),t=performance.now();if(model){if(autoRotate)model.rotation.y+=.003;model.position.y=.08+Math.sin(t*.00115+(index*.77))*.014;model.rotation.x=Math.sin(t*.0008+index)*.006;const w=model.userData.wings||[];w.forEach((x)=>{const amp=model.userData.speciesKey==='dragonfly'?.18:.12;x.o.rotation.z=x.base+Math.sin(t*.014+x.phase)*amp;});}if(mixer)mixer.update(dt);camera.position.z=THREE.MathUtils.lerp(camera.position.z,targetCam.z,.06);camera.position.y=THREE.MathUtils.lerp(camera.position.y,targetCam.y,.06);controls.target.y=THREE.MathUtils.lerp(controls.target.y,targetCam.ty,.06);controls.update();renderer.render(scene,camera);}

async function boot(){
 bind();clock();setInterval(clock,1000);renderCards();initScene();updateUI(DATA[0]);setLoad(6,'INITIALISING OPTICAL ARRAY');
 try{setLoad(16,'PRELOADING PRIMARY + NEIGHBOURS');const [g]=await Promise.all([loadModel(DATA[0],true),loadModel(DATA[1]),loadModel(DATA[7])]);model=g;model.userData.speciesKey='butterfly';setupMotion(model,DATA[0]);scene.add(model);setLoad(92,'CALIBRATING LIGHT + SHADOW');await new Promise(r=>setTimeout(r,140));setLoad(100,'CATALOGUE READY');document.body.classList.add('ready');setTimeout(()=>ui.preloader.remove(),420);preloadNeighbors();}catch(err){console.error(err);document.body.classList.add('ready');ui.preloader.remove();}tick();}
boot();
