/* INSECTA V15.2 FINAL — mobile/glass/environment interaction pass */
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/loaders/DRACOLoader.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/controls/OrbitControls.js';
import * as SkeletonUtils from 'https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/utils/SkeletonUtils.js';

const DATA = [
 {key:'butterfly',name:'Butterfly',latin:'Danaus plexippus',order:'Lepidoptera',family:'Nymphalidae',range:'Worldwide',role:'Pollinator',diet:'Nectar',size:'8.5–10.5 cm',life:'2–6 weeks adult',color:0xffa63d,card:'butterfly.jpg',summary:'A pollinator whose wing scales create visual signalling, camouflage and thermoregulation.',note:'Pollination, food webs and seasonal migration make butterflies valuable ecological indicators.',anatomy:[['HEAD + ANTENNAE','Sensory antennae and compound eyes orient the butterfly toward odours, movement and light.','SENSORY SYSTEM'],['WING SURFACE','Microscopic wing scales scatter light and contribute to colour, signalling and camouflage.','FLIGHT SURFACE'],['THORAX + ABDOMEN','Flight muscles sit in the thorax while the abdomen contains major digestive and reproductive organs.','CORE BODY']]},
 {key:'bee',name:'Honey Bee',latin:'Apis mellifera',order:'Hymenoptera',family:'Apidae',range:'Worldwide',role:'Pollinator',diet:'Nectar + pollen',size:'12–15 mm',life:'~6 weeks worker',color:0xf1b84b,card:'bee.jpg',summary:'A social pollinator with a specialised pollen basket and complex colony communication.',note:'Bees support flowering plant reproduction and form tightly coordinated social colonies.',anatomy:[['HEAD + EYES','Compound eyes detect motion and colour while antennae provide chemical and tactile information.','SENSORY SYSTEM'],['WINGS + FLIGHT MUSCLES','Two pairs of wings are coupled in flight; rapid wing beats support hovering and precise navigation.','FLIGHT SYSTEM'],['ABDOMEN + STINGER','The abdomen houses digestive and reproductive organs; workers have a defensive stinger.','DEFENCE + CORE']]},
 {key:'ant',name:'Ant',latin:'Formica rufa',order:'Hymenoptera',family:'Formicidae',range:'Europe + Asia',role:'Soil engineer',diet:'Omnivorous',size:'4–9 mm',life:'Weeks–years',color:0xb46d45,card:'ant.jpg',summary:'A colony-driven soil engineer with extreme cooperative behaviour and specialised caste roles.',note:'Ants aerate soil, redistribute nutrients and help shape microhabitats.',anatomy:[['HEAD + MANDIBLES','The head carries sensory antennae and powerful mandibles used for feeding, defence and carrying.','SENSORY + TOOLS'],['THORAX + LEGS','The thorax anchors six jointed legs that provide traction and rapid ground locomotion.','LOCOMOTION'],['ABDOMEN','The abdomen contains major internal organs and chemical communication structures used by the colony.','CORE BODY']]},
 {key:'dragonfly',name:'Dragonfly',latin:'Anax imperator',order:'Odonata',family:'Aeshnidae',range:'Africa + Eurasia',role:'Predator',diet:'Predatory insects',size:'66–84 mm',life:'Weeks–months adult',color:0x54bdc4,card:'dragonfly.jpg',summary:'A precision aerial predator with independent wing control and exceptional visual acuity.',note:'Dragonflies are efficient aerial predators and useful signals of freshwater ecosystem health.',anatomy:[['HEAD + COMPOUND EYES','Huge compound eyes provide a wide visual field for tracking prey during aerial pursuit.','VISION SYSTEM'],['FOUR WINGS','Each wing can contribute independently to lift, braking and manoeuvring for precise aerial control.','FLIGHT SYSTEM'],['ABDOMEN','The long abdomen balances the body in flight and carries respiratory, digestive and reproductive systems.','CORE BODY']]},
 {key:'ladybug',name:'Ladybird',latin:'Coccinella septempunctata',order:'Coleoptera',family:'Coccinellidae',range:'Northern Hemisphere',role:'Biocontrol',diet:'Aphids',size:'5–8 mm',life:'1 year',color:0xe14f48,card:'ladybug.jpg',summary:'A compact beetle whose warning colours advertise chemical defences to predators.',note:'Ladybirds help regulate aphid populations and can protect crops naturally.',anatomy:[['HEAD + ANTENNAE','The small head carries compound eyes and short antennae that help locate prey and environmental cues.','SENSORY SYSTEM'],['ELYTRA + WINGS','The coloured wing covers protect folded flight wings beneath the hard beetle shell.','ARMOUR + FLIGHT'],['ABDOMEN + DEFENCE','The abdomen is protected by the elytra and can support chemical defence responses when threatened.','DEFENCE SYSTEM']]},
 {key:'housefly',name:'House Fly',latin:'Musca domestica',order:'Diptera',family:'Muscidae',range:'Worldwide',role:'Decomposer',diet:'Liquids / decaying matter',size:'6–7 mm',life:'15–30 days',color:0x9fb7be,card:'housefly.jpg',summary:'A rapid-lifecycle decomposer with halteres that stabilise flight and compound eyes for motion detection.',note:'Flies recycle organic matter and transfer nutrients through food webs.',anatomy:[['HEAD + COMPOUND EYES','Large compound eyes detect rapid changes in the visual field while antennae and mouthparts sample the environment.','SENSORY SYSTEM'],['WING + HALTERE','One functional wing pair drives flight; tiny halteres act as gyroscopic sensors for balance.','FLIGHT CONTROL'],['ABDOMEN','The segmented abdomen contains digestive and reproductive organs and supports the fly’s rapid lifecycle.','CORE BODY']]},
 {key:'cockroach',name:'Cockroach',latin:'Periplaneta americana',order:'Blattodea',family:'Blattidae',range:'Worldwide',role:'Decomposer',diet:'Omnivorous',size:'34–53 mm',life:'1–2 years',color:0x9a704e,card:'cockroach.jpg',summary:'A resilient detritivore built around a flexible exoskeleton, sensitive antennae and rapid locomotion.',note:'Cockroaches are resilient detritivores that participate in nutrient cycling.',anatomy:[['HEAD + ANTENNAE','Long antennae continuously sample chemical and tactile information around the animal.','SENSORY SYSTEM'],['THORAX + LEGS','The thorax anchors six powerful legs built for fast, low-profile movement across uneven surfaces.','LOCOMOTION'],['ABDOMEN + WINGS','The segmented abdomen protects internal organs; adult cockroaches may use their wings during movement.','CORE + FLIGHT']]},
 {key:'mosquito',name:'Mosquito',latin:'Aedes aegypti',order:'Diptera',family:'Culicidae',range:'Tropical + subtropical',role:'Pollinator / vector',diet:'Nectar / blood (female)',size:'3–6 mm',life:'~2–4 weeks',color:0x7182b6,card:'mosquito.jpg',summary:'A lightweight dipteran with a specialised proboscis and sensory antennae tuned to chemical cues.',note:'Mosquitoes occupy aquatic and terrestrial food webs; some species are important disease vectors.',anatomy:[['HEAD + ANTENNAE','Antennae and sensory palps detect odours, carbon dioxide and other cues that help locate hosts.','SENSORY SYSTEM'],['PROBOSCIS','The elongated mouthpart is specialised for piercing and feeding; females can take blood meals.','FEEDING SYSTEM'],['WINGS + ABDOMEN','A single wing pair provides flight while the abdomen expands to accommodate a blood meal and eggs.','FLIGHT + CORE']]}
];

const $=id=>document.getElementById(id);
const ui={
 preloader:$('preloader'),loadStage:$('loadStage'),loadPct:$('loadPct'),loadBar:$('loadBar'),canvas:$('mainCanvas'),viewer:$('viewer'),
 title:$('specimenTitle'),latin:$('specimenLatin'),kicker:$('taxKicker'),no:$('specimenNo'),cards:$('cards'),
 researchBtn:$('researchToggle'),researchStep:$('researchStep'),researchTitle:$('researchTitle'),researchSub:$('researchSub'),researchStrip:$('researchStrip'),
 detail:$('detailHud'),detailTitle:$('detailTitle'),detailText:$('detailText'),detailMeta:$('detailMeta'),
 order:$('order'),family:$('family'),range:$('range'),role:$('role'),diet:$('diet'),size:$('size'),life:$('life'),summary:$('summary'),
 profile:$('profile'),mobileInfoTrigger:$('mobileInfoTrigger'),infoPanel:$('infoPanel'),infoTitle:$('infoTitle'),infoText:$('infoText'),infoNote:$('infoNote'),infoDiet:$('infoDiet'),infoSize:$('infoSize'),infoLife:$('infoLife'),
 sound:$('soundBtn'),stageHint:$('stageHint')
};
let scene,camera,renderer,controls,loader,draco;
let lastTime=performance.now(),elapsed=0,index=0,research=0,autoRotate=true,soundOn=false,transitionLock=false;
let currentRig=null,currentModel=null,currentMixer=null,viewTween=null;

let targetCam={z:5.2,y:.65,tx:0,ty:.65};
const cache=new Map(),loading=new Map(); let sharedLogoTexture=null;
const viewStates=[
 {id:'01',title:'WHOLE SPECIMEN',sub:'Full specimen · default presentation',mode:'whole'},
 {id:'02',title:'HEAD / SENSORY SYSTEM',sub:'Macro view · head, eyes & antennae',mode:'head'},
 {id:'03',title:'CORE BODY / LOCOMOTION',sub:'Macro view · thorax, abdomen & movement',mode:'body'},
 {id:'04',title:'WINGS / FLIGHT SURFACE',sub:'Macro view · wings, elytra & flight structures',mode:'wings'}
];
const audio={ctx:null,beep(type='click'){if(!soundOn)return;try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();this.ctx.resume();const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.connect(g);g.connect(this.ctx.destination);const t=this.ctx.currentTime;o.type='sine';o.frequency.setValueAtTime(type==='switch'?210:type==='pin'?640:420,t);o.frequency.exponentialRampToValueAtTime(type==='switch'?430:260,t+.1);g.gain.setValueAtTime(.016,t);g.gain.exponentialRampToValueAtTime(.001,t+.11);o.start(t);o.stop(t+.12);}catch{}}};


const CARD_COUNT=DATA.length;
const FOCUS={
 butterfly:[[-.42,.72],[0,.42],[.08,.66]],
 bee:[[-.46,.72],[0,.48],[.10,.72]],
 ant:[[-.50,.68],[.05,.45],[.15,.48]],
 dragonfly:[[-.50,.70],[.08,.48],[.12,.64]],
 ladybug:[[-.38,.67],[0,.46],[.04,.62]],
 housefly:[[-.43,.70],[0,.48],[.06,.72]],
 cockroach:[[-.46,.70],[.06,.44],[.10,.68]],
 mosquito:[[-.48,.71],[.08,.45],[.10,.67]]
};
function setLoad(p,text){ui.loadPct.textContent=p+'%';ui.loadStage.textContent=text;ui.loadBar.style.width=p+'%';}
function pathFor(d){return `./models/${d.key==='mosquito'?'mosquito_3d_model_free':d.key}.glb`;}
function cloneScene(src){return SkeletonUtils.clone(src);}
function resize(){if(!renderer||!camera||!ui.canvas)return;const r=ui.canvas.parentElement.getBoundingClientRect();camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio||1,matchMedia('(max-width:820px)').matches?1.2:1.45));renderer.setSize(r.width,r.height,false);}
function initScene(){
 scene=new THREE.Scene(); camera=new THREE.PerspectiveCamera(30,1,.05,100); camera.position.set(0,.72,5.15);
 renderer=new THREE.WebGLRenderer({canvas:ui.canvas,alpha:true,antialias:true,powerPreference:'high-performance'}); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.28; renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFShadowMap;
 scene.add(new THREE.HemisphereLight(0xbfe8ff,0x05070b,.95));
 const key=new THREE.DirectionalLight(0xffefd5,3.1); key.position.set(4.5,7,4.8); key.castShadow=true; key.shadow.mapSize.set(2048,2048); key.shadow.camera.near=.2; key.shadow.camera.far=26; key.shadow.camera.left=-6; key.shadow.camera.right=6; key.shadow.camera.top=6; key.shadow.camera.bottom=-6; key.shadow.bias=-.00025; scene.add(key);
 const fill=new THREE.DirectionalLight(0x74dfff,1.15); fill.position.set(-4,2.7,4.2); scene.add(fill);
 const rim=new THREE.DirectionalLight(0xdbeeff,1.45); rim.position.set(-3.5,5,-5.5); scene.add(rim);
 const warm=new THREE.PointLight(0xffb96c,.70,10); warm.position.set(2,1.4,3); scene.add(warm);
 loader=new GLTFLoader(); draco=new DRACOLoader(); draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.185.1/examples/jsm/libs/draco/'); draco.preload(); loader.setDRACOLoader(draco);
 controls=new OrbitControls(camera,ui.canvas); controls.enablePan=false; controls.enableDamping=true; controls.dampingFactor=.075; controls.enableZoom=true; controls.zoomSpeed=.85; controls.minDistance=1.35; controls.maxDistance=6.8; controls.minPolarAngle=Math.PI*.32; controls.maxPolarAngle=Math.PI*.66; controls.target.set(0,.72,0);
 window.addEventListener('resize',resize,{passive:true}); window.visualViewport?.addEventListener('resize',resize,{passive:true}); resize();
}
function tuneMaterials(root){root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){if(!m)continue;if(m.map)m.map.colorSpace=THREE.SRGBColorSpace;if(m.color)m.color.set(0xffffff);if('roughness' in m)m.roughness=Math.max(.26,m.roughness??.5);if('metalness' in m)m.metalness=Math.min(.16,m.metalness??0);m.needsUpdate=true;}});}
function normalize(root,key){root.position.set(0,0,0);root.rotation.set(0,0,0);root.scale.setScalar(1);const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3());const target={butterfly:3.0,bee:2.82,ant:2.82,dragonfly:3.05,ladybug:2.8,housefly:2.9,cockroach:2.9,mosquito:2.9}[key]||2.9;const k=target/(Math.max(size.x,size.y,size.z)||1);root.scale.setScalar(k);root.userData.speciesKey=key;return root;}
function safeClips(animations){return (animations||[]).map(c=>{const tracks=(c.tracks||[]).filter(t=>t&&typeof t.createInterpolant==='function'&&t.times?.length&&t.values?.length);return tracks.length?new THREE.AnimationClip(c.name||'specimen',c.duration,tracks):null;}).filter(Boolean);}
function collectMotionNodes(root,key){const wings=[],legs=[];root.traverse(o=>{const n=(o.name||'').toLowerCase();if(/wing|forewing|hindwing|wingroot|halter|ala/.test(n))wings.push({o,bz:o.rotation.z,bx:o.rotation.x,phase:wings.length*.83}); if(/leg|femur|tibia|tarsus|coxa|mandible|antenna|proboscis/.test(n))legs.push({o,bz:o.rotation.z,bx:o.rotation.x,phase:legs.length*.59});}); return {wings,legs};}
function setupMotion(root,d){currentMixer=null;const clips=safeClips(root.userData.animations||[]);if(clips.length){try{currentMixer=new THREE.AnimationMixer(root);for(const clip of clips){const action=currentMixer.clipAction(clip);action.reset().play();}}catch(err){console.warn('Animation clips skipped for',d.key,err);currentMixer=null;}}root.userData.motion=collectMotionNodes(root,d.key);}
function createPedestal(d){const stage=new THREE.Group();stage.name='FloatingSpecimenBase';
 const lower=new THREE.Mesh(new THREE.CylinderGeometry(1.78,1.92,.20,96),new THREE.MeshStandardMaterial({color:0x0b1118,metalness:.82,roughness:.27}));lower.castShadow=true;lower.receiveShadow=true;stage.add(lower);
 const plate=new THREE.Mesh(new THREE.CylinderGeometry(1.61,1.68,.08,96),new THREE.MeshStandardMaterial({color:0x1b2732,metalness:.72,roughness:.28}));plate.position.y=.12;plate.castShadow=true;plate.receiveShadow=true;stage.add(plate);
 const rim=new THREE.Mesh(new THREE.TorusGeometry(1.57,.045,18,112),new THREE.MeshStandardMaterial({color:0x8be9ff,emissive:0x21677e,emissiveIntensity:.7,metalness:.35,roughness:.22}));rim.rotation.x=Math.PI/2;rim.position.y=.18;stage.add(rim);
 const inner=new THREE.Mesh(new THREE.TorusGeometry(1.25,.016,12,96),new THREE.MeshStandardMaterial({color:0xe8bf73,emissive:0x62491e,emissiveIntensity:.27,metalness:.48,roughness:.26}));inner.rotation.x=Math.PI/2;inner.position.y=.185;stage.add(inner);
 const logoMat=sharedLogoTexture?new THREE.MeshBasicMaterial({map:sharedLogoTexture,transparent:true,opacity:.9,depthWrite:false}):new THREE.MeshBasicMaterial({color:0x8bdfff});const logo=new THREE.Mesh(new THREE.CircleGeometry(.50,64),logoMat);logo.rotation.x=-Math.PI/2;logo.position.y=.194;stage.add(logo);
 const contact=new THREE.Mesh(new THREE.RingGeometry(.53,.72,64),new THREE.MeshBasicMaterial({color:0x79e1ff,transparent:true,opacity:.08,depthWrite:false,blending:THREE.AdditiveBlending}));contact.rotation.x=-Math.PI/2;contact.position.y=.20;stage.add(contact);
 stage.add(new THREE.PointLight(d.color,.23,4));return stage;}
function fitModelToBase(root){const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3());const radial=Math.hypot(size.x,size.z)/2;const maxRad=1.50;const maxH=3.05;let s=1;if(radial>maxRad)s=Math.min(s,maxRad/radial);if(size.y*s>maxH)s=Math.min(s,maxH/size.y);root.scale.multiplyScalar(s);return new THREE.Box3().setFromObject(root);}
function buildFloatingStage(root,d){const rig=new THREE.Group();rig.name='SpecimenRig';const stage=createPedestal(d);stage.position.y=-.42;rig.add(stage);let box=fitModelToBase(root);const top=stage.position.y+.20;root.position.y+=top-box.min.y+.012;root.position.x=0;root.position.z=0;rig.add(root);box=new THREE.Box3().setFromObject(root);rig.userData={stage,model:root,modelBox:box,modelSize:box.getSize(new THREE.Vector3()),speciesKey:d.key};return rig;}
function currentRigMotion(t){if(!currentRig||!currentModel)return;const bob=Math.sin(t*.00105)*.010;currentRig.position.y=bob;if(autoRotate)currentRig.rotation.y+=.0015;currentRig.rotation.z=Math.sin(t*.00047)*.0028;const motion=currentModel.userData.motion;if(!motion)return;const key=currentModel.userData.speciesKey;if(currentMixer)return;
 if(motion.wings.length){for(const n of motion.wings){let amp=key==='dragonfly'?.055:key==='butterfly'?.042:key==='bee'?.038:key==='housefly'?.048:key==='mosquito'?.052:.025;n.o.rotation.z=n.bz+Math.sin(t*.0118+n.phase)*amp;n.o.rotation.x=n.bx+Math.cos(t*.0118+n.phase)*amp*.08;}}
 else if(motion.legs.length){for(const n of motion.legs){const amp=key==='ant'?.018:key==='ladybug'?.012:key==='cockroach'?.014:.010;n.o.rotation.z=n.bz+Math.sin(t*.0055+n.phase)*amp;n.o.rotation.x=n.bx+Math.cos(t*.0055+n.phase)*amp*.35;}}
}
async function loadModel(d,critical=false){if(cache.has(d.key))return cloneScene(cache.get(d.key));if(loading.has(d.key))return cloneScene(await loading.get(d.key));const p=new Promise((resolve,reject)=>loader.load(pathFor(d),g=>resolve(g),e=>{if(critical&&e.total){const pct=Math.min(74,16+Math.round(e.loaded/e.total*58));setLoad(pct,`DECODING ${d.name.toUpperCase()}`);}},reject)).then(g=>{g.scene.userData.animations=g.animations||[];tuneMaterials(g.scene);normalize(g.scene,d.key);cache.set(d.key,g.scene);return g.scene;});loading.set(d.key,p);try{return cloneScene(await p);}finally{loading.delete(d.key);}}
function updateUI(d){ui.title.textContent=d.name;ui.latin.textContent=d.latin;ui.kicker.textContent=`${d.order.toUpperCase()} // ${d.family.toUpperCase()}`;ui.no.textContent=String(index+1).padStart(2,'0');ui.order.textContent=d.order;ui.family.textContent=d.family;ui.range.textContent=d.range;ui.role.textContent=d.role;document.documentElement.style.setProperty('--accent',`#${d.color.toString(16).padStart(6,'0')}`);}
function positionCards(animate=true){if(!ui.cards)return;const cards=[...ui.cards.children];cards.forEach(el=>{const i=Number(el.dataset.index);let rel=i-index;if(rel>4)rel-=CARD_COUNT;if(rel<-4)rel+=CARD_COUNT;const angle=rel*12;const rad=angle*Math.PI/180;const x=Math.sin(rad)*340,y=(1-Math.cos(rad))*44;const scale=rel===0?1.18:Math.max(.64,1-Math.abs(rel)*.10);const op=rel===0?1:Math.max(.24,.84-Math.abs(rel)*.08);el.style.setProperty('--x',`${x}px`);el.style.setProperty('--y',`${y}px`);el.style.setProperty('--scale',scale);el.style.setProperty('--rot',`${angle*.20}deg`);el.style.setProperty('--ry',`${-angle}deg`);el.style.setProperty('--op',op);el.style.setProperty('--z',20-Math.abs(rel));el.classList.toggle('is-active',rel===0);const badge=el.querySelector('.card-active');if(rel===0&&!badge){const s=document.createElement('span');s.className='card-active';s.textContent='ACTIVE';el.appendChild(s);}if(rel!==0&&badge)badge.remove();});}
function renderCards(){ui.cards.innerHTML='';DATA.forEach((d,i)=>{const b=document.createElement('button');b.className='specimen-card';b.type='button';b.dataset.index=i;b.innerHTML=`<img src="./assets/cards/${d.card}" alt="${d.name}" loading="lazy"><span class="card-gloss"></span><span class="card-number">${String(i+1).padStart(2,'0')}</span><span class="card-name">${d.name}</span><span class="card-latin">${d.latin}</span>`;b.addEventListener('click',()=>switchTo(i));ui.cards.appendChild(b);});positionCards(false);}
function setViewGoal(goal,immediate=false){targetCam=goal;if(!camera||!controls)return;if(immediate){camera.position.set(goal.x,goal.y,goal.z);controls.target.set(goal.tx,goal.ty,0);viewTween=null;controls.enabled=true;return;}viewTween={start:performance.now(),duration:520,fromPos:camera.position.clone(),fromTarget:controls.target.clone(),toPos:new THREE.Vector3(goal.x,goal.y,goal.z),toTarget:new THREE.Vector3(goal.tx,goal.ty,0)};controls.enabled=false;}
function applyResearch(show=true){const d=DATA[index],v=viewStates[research];ui.researchStep.textContent=v.id+' / 04';ui.researchBtn.innerHTML=`<small>${v.id} / 04</small><span>RESEARCH VIEW</span><em>CLICK TO CYCLE</em>`;ui.researchTitle.textContent=v.title;ui.researchSub.textContent= research===0 ? v.sub : d.anatomy[research-1][0];
 const box=currentRig?.userData.modelBox;const focus=FOCUS[d.key]?.[Math.max(0,research-1)]||[0,.55];if(box){const h=Math.max(.1,box.max.y-box.min.y);if(research===0)setViewGoal({x:0,y:.72,z:5.15,tx:0,ty:.72});else{const fx=focus[0],fy=box.min.y+h*focus[1];setViewGoal({x:fx*1.05,y:fy,z:2.25,tx:fx,ty:fy});}}else setViewGoal({x:0,y:.72,z:5.15,tx:0,ty:.72});
 ui.viewer?.classList.toggle('view-macro',research>0);if(show){ui.researchStrip.classList.add('show');clearTimeout(window.__rs);window.__rs=setTimeout(()=>ui.researchStrip.classList.remove('show'),1050);}}
function stepResearch(dir){research=(research+dir+4)%4;applyResearch(true);audio.beep('click');}
function openDetail(i,sound=true){const d=DATA[index],a=d.anatomy[i%3];ui.detailTitle.textContent=a[0];ui.detailText.textContent=a[1];ui.detailMeta.textContent=a[2];ui.detail.dataset.open='1';if(sound)audio.beep('pin');}
function closeDetail(){ui.detail.dataset.open='0';}
function openInfo(){const d=DATA[index];ui.infoTitle.textContent=`${d.name} · ${d.latin}`;ui.infoText.textContent=d.summary;ui.infoNote.textContent=d.note;ui.infoDiet.textContent=d.diet;ui.infoSize.textContent=d.size;ui.infoLife.textContent=d.life;ui.infoPanel.dataset.open='1';if(ui.profile)ui.profile.dataset.mobileOpen='0';if(ui.mobileInfoTrigger)ui.mobileInfoTrigger.setAttribute('aria-expanded','false');}
function closeInfo(){ui.infoPanel.dataset.open='0';}
function switchTo(next){if(transitionLock)return;const target=(next+CARD_COUNT)%CARD_COUNT;if(target===index)return;transitionLock=true;const old=currentRig;const direction=((target-index+CARD_COUNT)%CARD_COUNT)<=4?1:-1;index=target;research=0;const d=DATA[index];updateUI(d);positionCards();closeInfo();closeDetail();audio.beep('switch');
 const finish=root=>{setupMotion(root,d);const rig=buildFloatingStage(root,d);rig.position.x=direction*.72;rig.rotation.y=direction*.16;rig.scale.setScalar(.90);scene.add(rig);currentRig=rig;currentModel=root;applyResearch(false);const start=performance.now();function reveal(){const p=Math.min(1,(performance.now()-start)/520),e=1-Math.pow(1-p,3);if(currentRig!==rig)return;rig.position.x=THREE.MathUtils.lerp(direction*.72,0,e);rig.rotation.y=THREE.MathUtils.lerp(direction*.16,0,e);rig.scale.setScalar(THREE.MathUtils.lerp(.90,1,e));if(p<1)requestAnimationFrame(reveal);else{if(old)scene.remove(old);transitionLock=false;preloadNeighbors();}}requestAnimationFrame(reveal);};
 if(cache.has(d.key))finish(cloneScene(cache.get(d.key)));else loadModel(d,true).then(finish).catch(err=>{console.error('Specimen load failed',err);transitionLock=false;});}
function preloadNeighbors(){const ids=[(index+1)%CARD_COUNT,(index+CARD_COUNT-1)%CARD_COUNT,(index+2)%CARD_COUNT,(index+CARD_COUNT-2)%CARD_COUNT];const run=async()=>{for(const id of ids){const d=DATA[id];if(!cache.has(d.key))try{await loadModel(d)}catch(err){console.warn('Preload failed',d.key,err);}}};(window.requestIdleCallback||((fn)=>setTimeout(fn,300)))(run);}
function inspectHit(e){if(!currentModel||!camera||transitionLock)return;const r=ui.canvas.getBoundingClientRect(),p=new THREE.Vector2(((e.clientX-r.left)/r.width)*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(p,camera);const hit=ray.intersectObject(currentModel,true)[0];if(!hit)return;const local=currentModel.worldToLocal(hit.point.clone()),box=new THREE.Box3().setFromObject(currentModel),h=(local.y-box.min.y)/(box.max.y-box.min.y||1);let part=h>.68?0:h<.34?2:1;if(Math.abs(local.x)>Math.max(.45,(box.max.x-box.min.x)*.24))part=1;openDetail(part,true);}
async function boot(){try{initScene();setLoad(7,'INITIALISING 3D ENGINE');try{sharedLogoTexture=await new THREE.TextureLoader().loadAsync('./assets/logo.png');sharedLogoTexture.colorSpace=THREE.SRGBColorSpace;}catch{}setLoad(12,'PRELOADING PRIMARY SPECIMEN');const primaryPromise=loadModel(DATA[0],true);const neighbors=Promise.all([loadModel(DATA[CARD_COUNT-1]),loadModel(DATA[1])]);const primary=await primaryPromise;await Promise.allSettled([neighbors]);setLoad(82,'BUILDING FLOATING SPECIMEN');setupMotion(primary,DATA[0]);currentModel=primary;currentRig=buildFloatingStage(primary,DATA[0]);scene.add(currentRig);updateUI(DATA[0]);renderCards();applyResearch(false);setLoad(96,'FINAL OPTICAL CALIBRATION');await new Promise(r=>setTimeout(r,130));setLoad(100,'CATALOGUE READY');setTimeout(()=>ui.preloader.classList.add('hidden'),180);preloadNeighbors();animate();}catch(err){console.error('BOOT FAILED',err);setLoad(100,'3D OFFLINE — SHOWING CATALOGUE');ui.preloader.classList.add('hidden');if(!scene){try{initScene();}catch{}}try{renderCards();}catch{}animate();}}
function bind(id,event,handler,options){const el=document.getElementById(id);if(!el)return;el.addEventListener(event,handler,options);}
function setupEvents(){
 bind('prevBtn','click',()=>switchTo(index-1)); bind('nextBtn','click',()=>switchTo(index+1)); bind('researchToggle','click',()=>stepResearch(1)); bind('expandBtn','click',()=>{openInfo();}); bind('mobileInfoTrigger','click',()=>{const isOpen=ui.profile?.dataset.mobileOpen==='1';if(ui.profile)ui.profile.dataset.mobileOpen=isOpen?'0':'1';if(ui.infoPanel)ui.infoPanel.dataset.open='0';if(ui.mobileInfoTrigger)ui.mobileInfoTrigger.setAttribute('aria-expanded',String(!isOpen));}); bind('closeInfo','click',closeInfo); bind('closeDetail','click',closeDetail);
 bind('autoBtn','click',e=>{autoRotate=!autoRotate;const span=e.currentTarget.querySelector('span');if(span)span.textContent=autoRotate?'ON':'OFF';});
 bind('resetBtn','click',()=>{research=0;closeInfo();closeDetail();if(ui.profile)ui.profile.dataset.mobileOpen='0';if(ui.mobileInfoTrigger)ui.mobileInfoTrigger.setAttribute('aria-expanded','false');applyResearch(false);setViewGoal({x:0,y:.72,z:5.15,tx:0,ty:.72});audio.beep('click');});
 bind('soundBtn','click',()=>{soundOn=!soundOn;ui.sound.textContent=soundOn?'SOUND ON':'SOUND OFF';ui.sound.classList.toggle('on',soundOn);audio.beep('click');});
 window.addEventListener('keydown',e=>{if(e.key==='ArrowRight')switchTo(index+1);else if(e.key==='ArrowLeft')switchTo(index-1);else if(e.key==='ArrowUp')stepResearch(-1);else if(e.key==='ArrowDown')stepResearch(1);else if(e.key==='Escape'){closeInfo();closeDetail();}});
 if(ui.canvas){let sx=0,sy=0,swiping=false;ui.canvas.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;swiping=false;},{passive:true});ui.canvas.addEventListener('pointermove',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))>45)swiping=true;},{passive:true});ui.canvas.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))>68){if(Math.abs(dx)>Math.abs(dy))switchTo(index+(dx<0?1:-1));else stepResearch(dy>0?1:-1);}else if(!swiping&&e.pointerType!=='touch')inspectHit(e);sx=sy=0;swiping=false;},{passive:true});ui.canvas.addEventListener('pointercancel',()=>{sx=sy=0;swiping=false;},{passive:true});
 }
 if(ui.cards){let csx=0;ui.cards.addEventListener('pointerdown',e=>{csx=e.clientX;},{passive:true});ui.cards.addEventListener('pointerup',e=>{const dx=e.clientX-csx;if(Math.abs(dx)>54)switchTo(index+(dx<0?1:-1));},{passive:true});}
}
function animate(){requestAnimationFrame(animate);const now=performance.now(),delta=Math.min(.05,(now-lastTime)/1000);lastTime=now;elapsed+=delta;if(currentMixer)currentMixer.update(delta);currentRigMotion(now);if(viewTween){const p=Math.min(1,(now-viewTween.start)/viewTween.duration),e=1-Math.pow(1-p,3);camera.position.lerpVectors(viewTween.fromPos,viewTween.toPos,e);controls.target.lerpVectors(viewTween.fromTarget,viewTween.toTarget,e);if(p>=1){camera.position.copy(viewTween.toPos);controls.target.copy(viewTween.toTarget);viewTween=null;controls.enabled=true;}}controls?.update();if(renderer&&scene&&camera)renderer.render(scene,camera);}
setupEvents();boot();
